redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\xampp\\htdocs\\blanchisserie_back\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
VITE_API_URL = "https://api.blanchisserie.sanoushop.com/api/v1"
VITE_WS_URL = "https://api.blanchisserie.sanoushop.com"
NODE_VERSION = "22"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]